# fly.toml app configuration file generated for remix-chistes on 2023-07-01T17:25:14+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "remix-chistes"
primary_region = "iad"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
